table '_Measures Table'
	lineageTag: 1c0fca73-00a9-4f8c-b112-a0e28b37a944

	measure 'Total Customers' = DISTINCTCOUNT(fact_churn[customerID])
		formatString: #,0
		lineageTag: 83d9ec6a-13aa-4eb7-b0f5-8215cac8d3ad

	measure 'Churned Customers' = CALCULATE([Total Customers], fact_churn[Churn_Flag] = 1)
		formatString: #,0
		lineageTag: b657b863-d089-40fb-aa3c-42a588efd9eb

	measure 'Churn Rate %' = DIVIDE([Churned Customers], [Total Customers])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 368bf9fe-7f65-45ba-aba3-389f8c1a66f8

	measure 'Total MRR' = SUM(fact_churn[MRR])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a76b52bb-ee56-409a-a063-42d41b4ae324

	measure 'Revenue at Risk' = CALCULATE([Total MRR], fact_churn[Churn_Flag] = 1)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ec1fbd87-642e-4238-a897-00de066d07cf

	measure 'Average MRR' = AVERAGE(fact_churn[MRR])
		lineageTag: 4626845a-8ddc-4295-b638-e78cf73896eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Tenure' = AVERAGE(fact_churn[MonthsSubscribed])
		lineageTag: 54ecb04f-ee08-4d21-bd46-4a4d51bf9c36

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Color Measure' =
			
			IF([Churn Rate %] >= 0.4, "#EF4444", BLANK())
		lineageTag: 49eb2b38-98c7-4268-8283-d520353df7c2

	measure 'Font Color' =
			
			IF([Churn Rate %] >= 0.4, "#FFFFFF", BLANK())
		lineageTag: a0e381fb-3e9c-4b4e-a22d-69e3a1a932ec

	measure CEO_Insight_Text =
			
			VAR MonthlyRisk = [Revenue at Risk]
			VAR NinetyDayRisk = MonthlyRisk * 3
			VAR Formatted90Day = FORMAT(NinetyDayRisk, "$#,#")
			VAR M2M_Risk = CALCULATE([Revenue at Risk], dim_contract[Contract] = "Month-to-month")
			VAR M2M_Pct = FORMAT(DIVIDE(M2M_Risk, MonthlyRisk), "0.0%")
			RETURN
			"If we take no action, we risk losing " & Formatted90Day & " in unrealized revenue over the next 90 days. " &
			"The financial bleeding is highly concentrated: Month-to-month contracts alone account for " & M2M_Pct & " of this total loss."
		lineageTag: ed2bafa8-fdd4-460e-a27a-8816b2ea61b3

	measure 'Dynamic Title' =
			
			VAR InternetLevel = COUNTROWS(VALUES(fact_churn[InternetService]))
			VAR ContractLevel = COUNTROWS(VALUES(dim_contract[Contract]))
			
			RETURN
			SWITCH(
			    TRUE(),
			    InternetLevel > 1, "Revenue at Risk — by Internet Service",
			    ContractLevel > 1, "Revenue at Risk — by Contract Type",
			    "Revenue at Risk"
			)
		lineageTag: 5fe7e250-5288-45c0-af63-d341205e11d1

	partition '_Measures Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

