table dim_contract
	lineageTag: fccb5a11-19aa-48a2-b9ad-7a760945d501

	column Contract_ID
		dataType: int64
		formatString: 0
		lineageTag: 7da0fc35-2c7d-4f35-8308-e896bad2734b
		summarizeBy: none
		sourceColumn: Contract_ID

		annotation SummarizationSetBy = Automatic

	column Contract
		dataType: string
		lineageTag: dd27e6ff-d289-407d-a0bc-5bbe42dfbe81
		summarizeBy: none
		sourceColumn: Contract

		annotation SummarizationSetBy = Automatic

	partition dim_contract = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\data-analysis-projects\saas-churn-analytics\data\processed\dim_contract.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Contract_ID", Int64.Type}, {"Contract", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

